name: conda-env3_7
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - kiwisolver=1.1
  - libpng=1.6
  - matplotlib=3.1
  - numpy=1.18
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.9.0
  - setuptools=46.1.3
  - six=1.14
  - sqlite=3.31
  - tornado=6.0.4
  - tqdm=4.38.0

